# Generated by Django 5.2.6 on 2025-10-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
